package io.project.finalwork.aitodo.data.model

import io.project.finalwork.aitodo.data.RepeatMode
import io.project.finalwork.aitodo.data.TaskEntity
import java.time.LocalDateTime
import java.util.UUID

data class TaskDraft(
    val id: String = UUID.randomUUID().toString(),
    val title: String,
    val deadline: LocalDateTime?,
    val reminder: LocalDateTime?,
    val repeatMode: RepeatMode
) {
    fun toTaskEntity(): TaskEntity {
        return TaskEntity(
            id = 0, // ID to be generated by Repository/ViewModel
            title = title,
            deadline = deadline,
            reminder = reminder,
            repeatMode = repeatMode,
            createdAt = LocalDateTime.now(),
            isCompleted = false,
            isPinned = false,
            isSelected = false
        )
    }
}
